"""AMP/Quick96 模型的GUI参数定义。"""
from faceswap.gui_app.param_defs import ParamDef, ParamGroup, ParamType

AMP_PARAM_DEFS: list[ParamDef] = [
    ParamDef(key="resolution", label="分辨率:", type=ParamType.INT, default=224,
             min_val=64, max_val=640, step=32, align_multiple=32, group=ParamGroup.BASIC,
             tooltip="训练分辨率(像素)，必须是32的倍数。"),
    ParamDef(key="face_type", label="人脸类型:", type=ParamType.STR, default="wf",
             choices=["wf", "head"], group=ParamGroup.BASIC,
             tooltip="wf=宽全脸, head=整个头部"),
    ParamDef(key="batch_size", label="批次大小:", type=ParamType.INT, default=8,
             min_val=1, max_val=32, group=ParamGroup.BASIC,
             tooltip="每次迭代处理的图像对数量。"),
    ParamDef(key="ae_dims", label="瓶颈维度:", type=ParamType.INT, default=256,
             min_val=32, max_val=1024, step=32, group=ParamGroup.BASIC,
             tooltip="AutoEncoder瓶颈维度。"),
    ParamDef(key="inter_dims", label="Inter维度:", type=ParamType.INT, default=1024,
             min_val=32, max_val=2048, step=32, group=ParamGroup.BASIC,
             tooltip="Inter层维度，应≥ae_dims。"),
    ParamDef(key="e_dims", label="编码器维度:", type=ParamType.INT, default=64,
             min_val=16, max_val=256, step=2, group=ParamGroup.BASIC,
             tooltip="编码器基础通道维度。"),
    ParamDef(key="d_dims", label="解码器维度:", type=ParamType.INT, default=64,
             min_val=16, max_val=256, step=2, group=ParamGroup.BASIC,
             tooltip="解码器基础通道维度。"),
    ParamDef(key="d_mask_dims", label="遮罩解码器维度:", type=ParamType.INT, default=22,
             min_val=8, max_val=128, step=2, group=ParamGroup.BASIC,
             tooltip="遮罩解码器基础通道维度。"),
    ParamDef(key="morph_factor", label="Morph因子:", type=ParamType.FLOAT, default=0.5,
             min_val=0.1, max_val=0.5, step=0.05, decimals=2, group=ParamGroup.BASIC,
             tooltip="Morph因子，控制inter_src/inter_dst混合比例。"),
    ParamDef(key="lr", label="学习率:", type=ParamType.FLOAT, default=5e-5,
             min_val=1e-6, max_val=1e-2, step=1e-5, decimals=7, group=ParamGroup.BASIC,
             tooltip="初始学习率。"),
    ParamDef(key="lr_dropout", label="学习率衰减:", type=ParamType.STR, default="n",
             choices=["n", "y", "ca"], group=ParamGroup.BASIC,
             tooltip="n=不启用, y=DFL模式(30%冻结+余弦震荡),\n"
                     "ca=余弦退火(单调下降到1%, 建议target_iter设为期望总步数,\n"
                     "从开启时刻起满lr退火到lr/100)。"),
    ParamDef(key="random_warp", label="随机变形", type=ParamType.BOOL, default=True,
             group=ParamGroup.BASIC, render_hint="new_row",
             tooltip="随机仿射变形，防止过拟合。"),
    ParamDef(key="random_src_flip", label="源随机翻转", type=ParamType.BOOL, default=True,
             group=ParamGroup.BASIC, tooltip="SRC图像随机水平翻转。"),
    ParamDef(key="random_dst_flip", label="目标随机翻转", type=ParamType.BOOL, default=True,
             group=ParamGroup.BASIC, tooltip="DST图像随机水平翻转。"),
    ParamDef(key="uniform_yaw", label="均匀偏航采样", type=ParamType.BOOL, default=False,
             group=ParamGroup.FACE_DETAIL, tooltip="均匀采样不同偏航角的人脸。"),
    ParamDef(key="blur_out_mask", label="模糊遮罩外区域", type=ParamType.BOOL, default=False,
             group=ParamGroup.FACE_DETAIL, tooltip="对遮罩外区域施加高斯模糊。"),
    ParamDef(key="ct_mode", label="颜色迁移:", type=ParamType.STR, default="none",
             choices=["none", "rct", "lct", "mkl", "idt", "sot"], group=ParamGroup.FACE_DETAIL,
             tooltip="SRC颜色迁移模式。"),
    ParamDef(key="gan_power", label="GAN强度:", type=ParamType.FLOAT, default=0.0,
             min_val=0.0, max_val=5.0, step=0.1, decimals=2, group=ParamGroup.LOSS_SAMPLING,
             tooltip="GAN对抗损失强度，0=不启用。"),
    ParamDef(key="gan_patch_size", label="GAN块大小:", type=ParamType.INT, default=28,
             min_val=3, max_val=640, step=1, group=ParamGroup.LOSS_SAMPLING,
             tooltip="GAN判别器Patch大小。"),
    ParamDef(key="gan_dims", label="GAN维度:", type=ParamType.INT, default=16,
             min_val=4, max_val=512, step=1, group=ParamGroup.LOSS_SAMPLING,
             tooltip="GAN判别器基础通道维度。"),
    ParamDef(key="amp_mode", label="混合精度:", type=ParamType.STR, default="fp16",
             choices=["fp32", "fp16", "bf16"], group=ParamGroup.OPTIMIZATION,
             tooltip="fp16=半精度加速(推荐), fp32=全精度。"),
    ParamDef(key="gradient_accumulation_steps", label="梯度累积步数:", type=ParamType.INT, default=1,
             min_val=1, max_val=16, group=ParamGroup.OPTIMIZATION,
             tooltip="梯度累积步数，等效增大batch size。\n1=不累积(默认)\nn=每n步才更新一次参数"),
    ParamDef(key="clipgrad", label="梯度裁剪", type=ParamType.BOOL, default=False,
             group=ParamGroup.OPTIMIZATION, tooltip="梯度全局L2范数裁剪(上限1.0)。"),
    ParamDef(key="enable_torch_compile", label="torch.compile加速", type=ParamType.BOOL, default=False,
             group=ParamGroup.OPTIMIZATION,
             tooltip="启用torch.compile编译加速(PyTorch≥2.0)。\n"
                     "默认关闭: 6GB显存下aot_eager后端只做AOT编译不做算子融合,\n"
                     "无实际加速反而增加编译时间和显存开销。\n"
                     "8GB+显存可用inductor后端获得真正加速(需PYTHONUTF8=1)。\n"
                     "首次迭代触发编译(约30~120秒), 编译失败自动降级为eager模式"),
    ParamDef(key="auto_batch", label="自动批次探测", type=ParamType.BOOL, default=False,
             group=ParamGroup.OPTIMIZATION,
             tooltip="启用后自动探测最大不OOM的batch size。\n探测结果不会超过手动设置的批次大小。"),
    ParamDef(key="pretrain", label="SRC-SRC预训练", type=ParamType.BOOL, default=False,
             group=ParamGroup.TRAINING_CONTROL,
             tooltip="使用SRC数据同时作为源和目标进行自重建预训练。\n"
                     "预训练时自动: dst目录=src目录, 关闭GAN, 开启uniform_yaw和随机翻转,\n"
                     "关闭颜色迁移。预训练后模型有更好的初始化, 可加速后续正式训练。"),
    ParamDef(key="target_iter", label="目标迭代数:", type=ParamType.INT, default=0,
             min_val=0, max_val=9999999, step=10000, group=ParamGroup.TRAINING_CONTROL,
             tooltip="0=无限训练。"),
    ParamDef(key="backup_interval", label="保存间隔:", type=ParamType.INT, default=0,
             min_val=0, max_val=1000000, step=1000, group=ParamGroup.TRAINING_CONTROL,
             tooltip="每隔多少次迭代自动保存。"),
]

QUICK96_PARAM_DEFS: list[ParamDef] = [
    ParamDef(key="batch_size", label="批次大小:", type=ParamType.INT, default=4,
             min_val=1, max_val=16, group=ParamGroup.BASIC,
             tooltip="Quick96全部参数硬编码(res=96,ae=128,e=64,d=64)，仅可调批次大小。"),
    ParamDef(key="random_src_flip", label="源随机翻转", type=ParamType.BOOL, default=True,
             group=ParamGroup.BASIC, tooltip="SRC图像随机水平翻转。"),
    ParamDef(key="random_dst_flip", label="目标随机翻转", type=ParamType.BOOL, default=True,
             group=ParamGroup.BASIC, tooltip="DST图像随机水平翻转。"),
    ParamDef(key="amp_mode", label="混合精度:", type=ParamType.STR, default="fp16",
             choices=["fp32", "fp16", "bf16"], group=ParamGroup.OPTIMIZATION,
             tooltip="fp16=半精度加速(推荐)。"),
    ParamDef(key="target_iter", label="目标迭代数:", type=ParamType.INT, default=0,
             min_val=0, max_val=9999999, step=10000, group=ParamGroup.TRAINING_CONTROL,
             tooltip="0=无限训练。"),
    ParamDef(key="backup_interval", label="保存间隔:", type=ParamType.INT, default=0,
             min_val=0, max_val=1000000, step=1000, group=ParamGroup.TRAINING_CONTROL,
             tooltip="每隔多少次迭代自动保存。"),
]
